version: '3.8'

services:
  worker-python:
    build: ./worker-python
    depends_on:
      - api-dotnet
    environment:
      - API_URL=http://api-dotnet:5000/webhook/preco

  api-dotnet:
    build:
      context: ./api-dotnet
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - logs:/logs
    environment:
      - ASPNETCORE_URLS=http://+:5000

volumes:
  logs: